### ISSUE TITLE
Handle all IDS of the robot

### ISSUE THREAD

**Issue by patfelix** [NAMeC-team/CRAbE_old#12]

**Comment by EtienneSchmitz** [comment]
Need #16

**Comment by EtienneSchmitz** [comment]
Resolve this issue before https://github.com/NAMeC-SSL/gestion/issues/4

**Comment by EtienneSchmitz** [comment]
Even with didn't handle #16, we handle all robots in https://github.com/NAMeC-SSL/CRAbE/pull/20
